using Application.Interfaces.UoW;
using Domain.Commands.Base;
using Domain.Interfaces.Repositories;
using MediatR;
using Domain.Interfaces.Repositories.Base;
using Domain.Interfaces.Entities.Base;
using AutoMapper;
using Application.Handlers.Default;
using Domain.ValueObjects.ResultInfo;
using Domain.Interfaces.Command.Base;
using Domain.Interfaces.ValueObjects;

namespace Application.Handlers.Bases
{
    public class BaseInsertHandler<TModel, TCommand>(IUnitOfWork unitOfWork, IRepositoryBase<TModel> repository, IMapper mapper) : BaseCommandHandler<TCommand, Result, IRepositoryBase<TModel>, TModel>(unitOfWork)
        where TModel : class, IEntity
        where TCommand : IRequest<Result>, IBaseInsertCommand
    {
        private readonly IRepositoryBase<TModel> _repository = repository;
        private readonly IMapper _mapper = mapper;

        public override async Task<Result> Handle(TCommand command, CancellationToken cancellationToken)
        {
            TModel entity = await MapAndValidate(command);

            if (result.Failed())
                return result;

            result = await ExecuteOperationsDataBaseAndBRs(entity);

            return result;
        }

        private async Task<Result> ExecuteOperationsDataBaseAndBRs(TModel entity)
        {
            result = await entity.ExecuteBusinnesRulesBeforeOperations(result);

            if (result.Failed())
                return result;

            IAutoGeneratedValue entityId = await InsertIntoBD(entity);

            result = new Result(entityId, []);

            await entity.ExecuteBusinnesRuleAfterOperations();

            return result;
        }

        private async Task<IAutoGeneratedValue> InsertIntoBD(TModel entity)
        {
            var entityId = await _repository.Insert(entity);

            await Commit();
            return entityId;
        }

        private async Task<TModel> MapAndValidate(TCommand command)
        {
            var entity = _mapper.Map<TModel>(_mapper.Map<TModel>(command));

            await Validate(entity);

            return entity;
        }
    }
}
