using API.Interfaces;
using Application.DTOs.Entities.Supplier;
using Application.DTOs.Filters;
using Application.Interfaces.DTOs;
using Application.Interfaces.Filters;
using Application.Interfaces.Services;
using Application.Interfaces.Services.Base;
using Application.Services;
using Domain.Commands.Supplier;
using Domain.Helpers;
using Domain.Interfaces.Command.Base;
using Domain.Interfaces.Entities.Base;
using Domain.Interfaces.ValueObjects;
using Domain.ValueObjects.ResultInfo;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace API.Controllers.Extension
{
    public class ControllerExtension<TInsertCommand, TUpdateCommand, TDeleteCommand, TFilter, TEntityListDTO, TEntityPagedListDTO, TEntity>(IMediator mediator, IServiceBase service) : ControllerBase
        where TInsertCommand : IRequest<Result>, IBaseInsertCommand
        where TUpdateCommand : IRequest<Result>, IBaseUpdateCommand
        where TDeleteCommand : IRequest<Result>
        where TFilter : IFilter
        where TEntityListDTO : IEntityDTO
        where TEntityPagedListDTO : IEntityDTO
        where TEntity : IEntity
    {
        private readonly IMediator _mediator = mediator;
        private readonly IServiceBase _service = service;

        [HttpPost]
        public virtual async Task<IActionResult> Post(TInsertCommand command)
        {
            return await MediatorSend(command, ResponseStatus.Created);
        }

        [HttpPut]
        public virtual async Task<IActionResult> Update(TUpdateCommand command)
        {
            return await MediatorSend(command, ResponseStatus.NoContent);
        }

        [HttpDelete]
        public virtual async Task<IActionResult> Delete(TDeleteCommand command)
        {
            return await MediatorSend(command, ResponseStatus.NoContent);
        }

        [HttpGet("List")]
        public virtual async Task<IActionResult> List([FromQuery] TFilter filter)
        {
            return BuildResult(await _service.List<TEntityListDTO, TFilter>(filter), ResponseStatus.Ok);
        }

        [HttpGet]
        public virtual async Task<IActionResult> Get(long id)
        {
            return BuildResult(await _service.GetById<TEntity>(id), ResponseStatus.Ok);
        }

        [HttpGet("exist")]
        public virtual async Task<IActionResult> Exist([FromQuery] TFilter filter)
        {
            return BuildResult(await _service.Exist(filter), ResponseStatus.Ok);
        }

        [HttpGet("count")]
        public virtual async Task<IActionResult> Count([FromQuery] TFilter filter)
        {
            return BuildResult(await _service.Count(filter), ResponseStatus.Ok);
        }

        [HttpGet("PagedList")]
        public virtual async Task<IActionResult> PagedList([FromQuery] TFilter filter, int pageNumber = 1, int pageSize = 10)
        {
            return BuildResult(await _service.PagedList<TEntityPagedListDTO, TFilter>(filter, pageNumber, pageSize), ResponseStatus.Ok);
        }

        #region Private Methods
        [NonAction]
        public async Task<IActionResult> MediatorSend<TCommand>(TCommand command, ResponseStatus responseStatus) where TCommand : IRequest<Result>
        {
            Result result = await _mediator.Send(command);

            return BuildResult(result, responseStatus);
        }

        [NonAction]
        public IActionResult BuildResult(Result result, ResponseStatus responseStatus, string routeGet = "Get")
        {
            if (result.Data == null && responseStatus != ResponseStatus.NoContent)
            {
                return NotFound(result.Errors);
            }
            else if (result.Failed())
            {
                return BadRequest(result.Errors);
            }
            
            switch (responseStatus)
            {
                case ResponseStatus.NoContent:
                    return NoContent();

                case ResponseStatus.Created:
                    if (result.Data is IAutoGeneratedValue autoGenValue)
                    {
                        return CreatedAtAction(routeGet, new { id = autoGenValue.Id }, autoGenValue.Id);
                    }
                    return BadRequest("Data de criação inválida.");

                case ResponseStatus.Ok:
                    return Ok(result.Data);

                default:
                    return Ok(result.Data);
            }
        }
        #endregion
    }
}
