using Domain.Interfaces.Repositories.Base;
using Domain.Interfaces.ValueObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.ValueObjects
{
    public class AutoGeneratedValue : IAutoGeneratedValue
    {
        private readonly Func<long> primaryKey;

        public AutoGeneratedValue(Func<long> primaryKeyFunc)
        {
            primaryKey = primaryKeyFunc;
        }

        public long Id => primaryKey?.Invoke() ?? 0;

        public override int GetHashCode()
        {
            return HashCode.Combine(primaryKey);
        }
    }
}
